import Head from "next/head";
import Header from "../components/Header";
import Intro from "../components/Intro";
import CategoryFeaturedBlogs from "../components/CategoryFeaturedBlogs";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Intro />
      <CategoryFeaturedBlogs
        categoryDesc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel iste distinctio fugiat quisquam reprehenderit sequi voluptate inventore libero quo cum?"
        category="tech"
      />
      <CategoryFeaturedBlogs
        categoryDesc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel iste distinctio fugiat quisquam reprehenderit sequi voluptate inventore libero quo cum?"
        category="otaku"
      />
      <CategoryFeaturedBlogs
        categoryDesc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel iste distinctio fugiat quisquam reprehenderit sequi voluptate inventore libero quo cum?"
        category="travel"
      />
      <div className="mx-auto w-11/12 lg:w-[58rem]">
        <hr className="w-full border-none h-[1px] text-primary bg-primary mb-8" />
      </div>
      <Footer />
    </div>
  );
}
