import Head from "next/head";
import Header from "../components/Header";
import Intro from "../components/Intro";
import CategoryFeaturedBlogs from "../components/CategoryFeaturedBlogs";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home({ categories }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header categories={categories} />
      <Intro />
      {categories.map((category) => {
        return <CategoryFeaturedBlogs key={category.id} category={category} />;
      })}
      <div className="mx-auto w-11/12 lg:w-[58rem]">
        <hr className="w-full border-none h-[1px] text-primary bg-primary mb-8" />
      </div>
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  let categories;

  const categoryArrRes = await fetch(
    `http://localhost:1337/api/categories?populate=*`,
    {
      headers: headers,
    }
  );

  const categoryArr = await categoryArrRes.json();
  categories = categoryArr.data;

  return {
    props: { categories }, // will be passed to the page component as props
  };
}
