import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";

const Slug = () => {
  const router = useRouter();
  const { slug } = router.query;

  return (
    <div>
      <Head>
        <title>Sayan Munshi - Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {slug}
    </div>
  );
};

export async function getServerSideProps(context) {
  const headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  let categories;

  const categoryArrRes = await fetch(
    `http://localhost:1337/api/categories?populate=*`,
    {
      headers: headers,
    }
  );

  const categoryArr = await categoryArrRes.json();

  categories = categoryArr.data;

  return {
    props: { categories }, // will be passed to the page component as props
  };
}

export default Slug;
